name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install dependencies
      run: composer install

    - name: Deploy application
      uses: atymic/deployer-php-action@0.3.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        deploy-path: /var/www/html
        repository: ${{ github.repository }}
        branch: main

    - name: Run tests
      run: phpunit
